### ISSUE TITLE
TODO for 0.1.0

### ISSUE THREAD

**Issue by androlo** [smartcontractproduction/dao#2]
- [x] Go over and clean up inheritance schemes.
- [x] Go over code docs.
- [x] Go over repo docs.
- [x] dao-core release ready.
- [x] dao-currency release ready.
- [x] dao-users release ready.
- [x] dao-votes release ready.

**Comment by androlo** [comment]
Fine for a 0.1.0.
