### ISSUE TITLE
TODO for 0.2.0

### ISSUE THREAD

**Issue by androlo** [smartcontractproduction/dao#3]
This will get milestone and revisions after the 0.1.0 alpha release.

- [ ] revisit tests, rewrite where needed, to make better.
- [ ] more javascript, deployment, tests, calling code, etc.
- [ ] lock down versions of everything external.

**If Solidity has fixes / upgrades**

- [ ] Complement docs, make better. More tags?
- [ ] Write new test-contracts for --formal. 

**Maybe**

- [ ] Administrative web-pages for basic components.
